# Generated by Django 5.2.1 on 2025-08-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('support_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherfeedback',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='teacherfeedback',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='authentication.teacherprofile'),
            preserve_default=False,
        ),
    ]
