# Generated by Django 5.2.1 on 2025-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='allow_student_recording_access',
            field=models.BooleanField(default=False),
        ),
    ]
