# Generated by Django 5.2.1 on 2025-08-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_topic_video_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.topic'),
        ),
    ]
