# Generated by Django 5.2.1 on 2025-08-28 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=100)),
                ('current_class', models.CharField(help_text='Current class/grade', max_length=50)),
                ('subjects', models.TextField(help_text='Subjects of interest (comma separated)')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or requests', null=True)),
                ('is_registered', models.BooleanField(default=False, help_text='Has this person registered as a student?')),
                ('is_processed', models.BooleanField(default=False, help_text='Has admin processed this query?')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for this query', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='User account if they registered later', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='student_que_email_57d4b1_idx'), models.Index(fields=['is_registered'], name='student_que_is_regi_8316d1_idx'), models.Index(fields=['is_processed'], name='student_que_is_proc_7dd6b0_idx'), models.Index(fields=['created_at'], name='student_que_created_4b91b7_idx')],
            },
        ),
    ]
